#!/usr/bin/env python3
"""
把 `e2e/anon_jwt_sse/.env.local` 的 Supabase/后端配置同步到 Web 的 Vite env。

目的：让本地开发时 Web 的 `VITE_SUPABASE_*` 与 E2E 的 `SUPABASE_*` 使用同一份 SSOT，避免手动复制漂移。

默认输入：  e2e/anon_jwt_sse/.env.local
默认输出：  web/.env.development.local

映射规则：
  SUPABASE_URL      -> VITE_SUPABASE_URL
  SUPABASE_ANON_KEY -> VITE_SUPABASE_ANON_KEY
  API_BASE / API_BASE_URL -> VITE_API_URL + VITE_PROXY_TARGET（自动去掉末尾 /api/v1）

注意：
  - 该脚本不会打印任何密钥内容，只打印写入了哪些 key。
  - `web/.env.development.local` 已被 gitignore 忽略，请勿提交密钥。
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Dict, Optional


def _parse_dotenv(path: Path) -> Dict[str, str]:
    if not path.exists():
        raise FileNotFoundError(str(path))
    data: Dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if (val.startswith("'") and val.endswith("'")) or (val.startswith('"') and val.endswith('"')):
            val = val[1:-1]
        data[key] = val
    return data


def _normalize_api_base(raw: str) -> str:
    v = (raw or "").strip()
    if not v:
        return ""
    v = v.rstrip("/")
    if v.endswith("/api/v1"):
        v = v[: -len("/api/v1")]
    return v


def _write_web_env(path: Path, *, supabase_url: str, supabase_anon_key: str, api_base: Optional[str]) -> list[str]:
    lines = [
        "# Auto-generated by scripts/dev/sync_e2e_env_to_web.py",
        "# Source of truth: e2e/anon_jwt_sse/.env.local",
        "",
        f"VITE_SUPABASE_URL={supabase_url}",
        f"VITE_SUPABASE_ANON_KEY={supabase_anon_key}",
    ]
    written = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]

    if api_base:
        api = _normalize_api_base(api_base)
        if api:
            lines += [
                f"VITE_API_URL={api}",
                f"VITE_PROXY_TARGET={api}",
            ]
            written += ["VITE_API_URL", "VITE_PROXY_TARGET"]

    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return written


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]
    src = Path(os.getenv("E2E_ENV_PATH") or (repo_root / "e2e/anon_jwt_sse/.env.local"))
    dst = Path(os.getenv("WEB_ENV_PATH") or (repo_root / "web/.env.development.local"))

    env = _parse_dotenv(src)
    supabase_url = (env.get("SUPABASE_URL") or "").strip().rstrip("/")
    supabase_anon_key = (env.get("SUPABASE_ANON_KEY") or "").strip()
    api_base = (env.get("API_BASE_URL") or env.get("API_BASE") or "").strip()

    missing = []
    if not supabase_url:
        missing.append("SUPABASE_URL")
    if not supabase_anon_key:
        missing.append("SUPABASE_ANON_KEY")
    if missing:
        print(f"Missing keys in {src.name}: {', '.join(missing)}")
        return 2

    written = _write_web_env(dst, supabase_url=supabase_url, supabase_anon_key=supabase_anon_key, api_base=api_base or None)
    print(f"Wrote {dst.relative_to(repo_root)} keys: {', '.join(written)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

